# NumPy Arrays


In [5]:
lst_1 = [1,2,3]
print(lst_1)

[1, 2, 3]


In [7]:
import numpy as np
arr = np.array(lst_1)

In [8]:
lst_2 = [[1,2,3], [4,5,6], [7,8,9]]
np.array(lst_2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## arange() Function

In [17]:
import numpy as np

arr_1 = np.arange(0,11,2)
print(arr_1)

[ 0  2  4  6  8 10]


### .zeros() & .ones()

In [4]:
import numpy as np

np.zeros(3)

array([0., 0., 0.])

In [6]:
import numpy as np

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
import numpy as np

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
import numpy as np

np.linspace(1,3,5)

array([1. , 1.5, 2. , 2.5, 3. ])

In [16]:
import numpy as np

np.ones((1,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]]])

### Identity Matrix

In [19]:
import numpy as np

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Random Matrix


In [22]:
import numpy as np

np.random.rand(5)

array([0.68821793, 0.56029658, 0.92133874, 0.3854493 , 0.23426639])

In [28]:
import numpy as np

np.random.rand(2,3)

array([[0.35343337, 0.45851574, 0.84393374],
       [0.58586801, 0.68601881, 0.10634565]])

In [30]:
import numpy as np

np.random.randn(2,3)

array([[ 1.06399615, -0.42922077,  0.84537385],
       [-0.36444844,  0.4788225 , -0.32259135]])

In [32]:
import numpy as np

np.random.randint(1, 100, 5)

array([64, 81, 69, 46, 22])

## Array Mehthods

In [41]:
import numpy as np
arr = np.arange(9)
print(arr)

arr = arr.reshape(3,3)
print(arr)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [67]:
import numpy as np

ranarr = np.random.randint(1,25, 10)
print(ranarr)

print(ranarr.max())


[15 14  9  5  8  8 16  8  7  8]
16


In [69]:
import numpy as np

ranarr = np.random.randint(1,25, 10)
print(ranarr)

print(ranarr.min())

[18 20  4 18  9 21  4 12  8 22]
4


In [75]:
print(ranarr)
print(ranarr.argmin())

[18 20  4 18  9 21  4 12  8 22]
2


In [91]:
arr = np.arange(0,10)
print(arr)

arr[0:5] = 100
print(arr)




[0 1 2 3 4 5 6 7 8 9]
[100 100 100 100 100   5   6   7   8   9]


In [99]:
arr_1 = np.arange(0, 11)
arr_copy = arr_1.copy()
arr_copy[:] = 100

print(arr_1)
print(arr_copy)

[ 0  1  2  3  4  5  6  7  8  9 10]
[100 100 100 100 100 100 100 100 100 100 100]


In [115]:
arr_2D = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
(arr_2D)

arr_2D[0][0]

5

In [117]:
arr_2D = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
(arr_2D)

arr_2D[0,0]

5

In [123]:
arr_2D = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2D[:2, 1:]

array([[10, 15],
       [25, 30]])

In [145]:
arr = np.arange(0,11)
arr_bool = arr > 5
arr[arr_bool]

array([ 6,  7,  8,  9, 10])

In [147]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

# NumPy Operations

## Array w Array Operations

In [27]:
matrix1 = np.array([[1, 3], 
             		[5, 7]])
             
matrix2 = np.array([[2, 6], 
                    [4, 8]])

result = np.dot(matrix1, matrix2)

result

array([[14, 30],
       [38, 86]])

In [181]:
arr = np.arange(0,11)
print(arr)
print(arr+arr)
print(arr-arr)
print(arr*arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0 0]
[  0   1   4   9  16  25  36  49  64  81 100]


## Scalar w Array

In [186]:
arr + 100


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [188]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [190]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])